env:
  ISOLATED: "true"
  MINE: "YOURS"
client_script:
  - -put --args README.md;;README_1.md
  - -get --args README.md;;README_1.md
before_script:
  - echo before_script
script:
  - echo script
after_script:
  - echo after_script