env:
  FOO: "BAR"
client_script:
  - -put --args cicd_flow.py;;cicd_flow.py
  - -get --args /etc/os-release;;os-release.txt
before_script:
  - cat /etc/os-release
script:
  - chmod +x cicd_flow.py
  - python3 cicd_flow.py
after_script:
  - echo "finished"