env:
  FOO: "BAR"
client_script:
  - -sys --args systeminfo
  - -sys --args echo;;"I am on client"
  - -put --args cicd_flow.py;;cicd_flow.py
#  - -get --args /etc/os-release;;os-release.txt
before_script:
  - echo "before_script"
script:
  - echo "script"
after_script:
  - echo "after_script"